apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.5.1
    replicas: 3
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true

      ## nodeport type 등록 -------
      - name: external
        port: 9094
        type: nodeport
        tls: false
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            nodePort: 32100
          brokers:
          - broker: 0
            advertisedHost: my-cluster.kafka.127.0.0.1.nip.io    # 각자의 Node IP로 변경
            nodePort: 32200
          - broker: 1
            advertisedHost: my-cluster.kafka.127.0.0.1.nip.io    # 각자의 Node IP로 변경
            nodePort: 32201
          - broker: 2
            advertisedHost: my-cluster.kafka.127.0.0.1.nip.io    # 각자의 Node IP로 변경
            nodePort: 32202
      ## nodeport type 등록 -------

    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.5"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}